### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by theodorzoulias** [SymboLinker/AwaitMultiple#1]
```c#
public static async Task<(T1, T2)> tasks<T1, T2>(Task<T1> task1, Task<T2> task2)
{
    var whenAll = Task.WhenAll(task1, task2);
    try
    {
        await whenAll;
    }
    catch
    {
        throw whenAll.Exception;
    }
    return (await task1, await task2);
}
```
I can see three problems with your implementation:

1. Poor method naming. Generally methods in C# are PascalCased verbs, not camelCased nouns. Microsoft's method `Task.WhenAll` doesn't abide to this rule, but it's a well thought exception that works well. The name `tasks` does not.
2. Missing `.ConfigureAwait(false)` on the `await whenAll`. This is a must for libraries.
3. Poor error handling. In case the `whenAll` completes as canceled the `whenAll.Exception` will be `null`, resulting in a nasty `NullReferenceException`. You could look at [this](https://stackoverflow.com/questions/30907650/foreachasync-with-result/71129678#71129678 "ForEachAsync with Result") StackOverflow answer for a better way of changing the result type of an asynchronous method while preserving all the exceptions. You could consider encapsulating the boilerplate code in an internal [`Then`](https://github.com/dotnet/runtime/issues/58692 "[API Proposal]: Then or ContinueWithResult extension method for Task") extension method, that you could use like this:

```c#
public static Task<(T1, T2)> NewBetterName<T1, T2>(Task<T1> task1, Task<T2> task2)
{
    return Task.WhenAll(task1, task2).Then(() => (task1.Result, task2.Result));
}
```
Notice the absence of the `async` keyword.

**Comment by SymboLinker** [comment]
Thanks for your feedback!

I have published `v1.0.2` that
- includes handling of `TaskCanceledException`s.
- uses `ConfigureAwait(false)`.

For "point 1" I would like to take some time pondering options. Ideally I would like to have a syntax like this:
```csharp
var (employees, books) = await [
   dbConnection.GetAllAsync<Employee>(),
   dbConnection.GetAllAsync<Book>(),
];
```
or stay as close as possible to that. Because `await` is a verb already, I like reading `await tasks` even if that is a naming violation because the latter is a method:
```csharp
var (books, employees) = await tasks(
   dbConnection.GetAllAsync<Books>(),
   dbConnection.GetAllAsync<Employees>());
```

Because the name of the package is `AwaitMultiple`, perhaps I should just go for `Multiple`:
```csharp
var (books, employees) = await Multiple(
   dbConnection.GetAllAsync<Books>(),
   dbConnection.GetAllAsync<Employees>());
```

**Comment by theodorzoulias** [comment]
```c#
public static async Task<(T1, T2)> tasks<T1, T2>(Task<T1> task1, Task<T2> task2)
{
    await AggregateExceptions(task1, task2);
    return (await task1, await task2);
}
```

Now there is a missing `.ConfigureAwait(false)` on the `await AggregateExceptions(task1, task2)`. In a library **all** awaits should be configured to not capture the context, otherwise some uses will result in deadlock.

As for how to `await` directly an array of tasks, without any name after the `await`, it might be possible with a `GetAwaiter` extension method for arrays. Someone has already done it for value-tuples ([TaskTupleAwaiter](https://github.com/buvinghausen/TaskTupleAwaiter)).

**Comment by SymboLinker** [comment]
> In a library all awaits should be configured to not capture the context, otherwise some uses will result in deadlock.

Hmm... that should become a default compiler setting for all libraries then. I'm glad I know about it now. Version `1.0.3` contains this fix.

**About an array of tasks**
I guess that it's not possible with arrays because they don't have per-element generic type information. Also, if it was possible, but the library would become as huge/complicated as the TaskTupleAwaiter library, I would not even do it. It's harder to understand and harder to maintain. Many thanks for the reference, though. The syntax is almost identical to what I earlier described as "ideal".

**About the naming violation**
I've decided to stick with the current naming. When reading
```csharp
var (books, employees) = await tasks(
   dbConnection.GetAllAsync<Books>(),
   dbConnection.GetAllAsync<Employees>());
```
I find it very natural to read, almost a like reading built-in C# keywords. Maybe this gets people positively interested and does it help them making their code easier to follow and maintain. When people feel distrust of the quality of the library because of this naming violation, they have a look at the source code and may contribute greatly :) All the better!

I will now close this issue. Thank you very much for your feedback / huge contributions!

**Comment by SymboLinker** [comment]
After all, I changed ([v2.0.0](https://www.nuget.org/packages/AwaitMultiple/2.0.0)) the method name from `tasks` to `Tasks` - still not a verb, but at least PascalCase :)

**Comment by SymboLinker** [comment]
FYI: some changes have been published after a [conversation in this thread](https://github.com/dotnet/csharplang/discussions/380#discussioncomment-11044733). 
To read the full conversation, you may need to click "Show .. previous replies".
